//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course2()
        {
            this.Examinations = new HashSet<Examination2>();
            this.PaperExamineds = new HashSet<PaperExamined2>();
        }
    
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public string CourseType { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<int> Session { get; set; }
        public string Technical { get; set; }
        public string DoubleSeating { get; set; }
        public string SimultaneousPaper { get; set; }
        public string CnblPaper { get; set; }
        public string SpecificRoom { get; set; }
        public string SpecificTimeslot { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> ExamWeight { get; set; }
        public string CGPA { get; set; }
        public Nullable<int> CreditHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination2> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperExamined2> PaperExamineds { get; set; }
    }
}
