//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination2
    {
        public string TimeslotID { get; set; }
        public string VenueID { get; set; }
        public string CourseCode { get; set; }
        public string ProgrammeCode { get; set; }
        public string PaperType { get; set; }
        public int Year { get; set; }
        public string ExamType { get; set; }
        public Nullable<int> SitFrom { get; set; }
        public Nullable<int> SitTo { get; set; }
    
        public virtual Course2 Course { get; set; }
        public virtual Venue2 Venue { get; set; }
    }
}
