//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvigilationDuty2
    {
        public int InvigilationDutyID { get; set; }
        public string TimeslotID { get; set; }
        public string VenueID { get; set; }
        public string Location { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string CatOfInvi { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Staff2 Staff { get; set; }
        public virtual Venue2 Venue { get; set; }
    }
}
