//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block2> Block2 { get; set; }
        public virtual DbSet<Course2> Course2 { get; set; }
        public virtual DbSet<Examination2> Examination2 { get; set; }
        public virtual DbSet<InvigilationDuty2> InvigilationDuty2 { get; set; }
        public virtual DbSet<PaperExamined2> PaperExamined2 { get; set; }
        public virtual DbSet<Room2> Room2 { get; set; }
        public virtual DbSet<Staff2> Staff2 { get; set; }
        public virtual DbSet<Venue2> Venue2 { get; set; }
    }
}
