//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperExamined2
    {
        public int StaffID { get; set; }
        public string CourseCode { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string FacultyCode { get; set; }
        public string PaperType { get; set; }
        public string LvlOfProgramme { get; set; }
        public string MaterialsByDECA { get; set; }
    
        public virtual Course2 Course { get; set; }
        public virtual Staff2 Staff { get; set; }
    }
}
