//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff2()
        {
            this.InvigilationDuties = new HashSet<InvigilationDuty2>();
            this.PaperExamineds = new HashSet<PaperExamined2>();
        }
    
        public int StaffID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public string FacultyCode { get; set; }
        public string Department { get; set; }
        public string isMuslim { get; set; }
        public string isTakingSTSPhD { get; set; }
        public string TypeOfEmploy { get; set; }
        public Nullable<int> NoOfSatSession { get; set; }
        public Nullable<int> NoAsQuarantineInvi { get; set; }
        public Nullable<int> NoAsReliefInvi { get; set; }
        public Nullable<int> NoOfExtraSession { get; set; }
        public string isChiefInvi { get; set; }
        public string isInviAbove2Years { get; set; }
        public string isInvi { get; set; }
        public string isExam { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string UniqueCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvigilationDuty2> InvigilationDuties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperExamined2> PaperExamineds { get; set; }
    }
}
