//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTimetabling2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venue2()
        {
            this.Examinations = new HashSet<Examination2>();
            this.InvigilationDuties = new HashSet<InvigilationDuty2>();
            this.Rooms = new HashSet<Room2>();
        }
    
        public string VenueID { get; set; }
        public string Location { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> MaximumProgramme { get; set; }
        public string PreferencePaper { get; set; }
        public string EastOrWest { get; set; }
        public string ExitLocation { get; set; }
        public Nullable<int> MaxColumn { get; set; }
        public Nullable<int> MaxRow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination2> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvigilationDuty2> InvigilationDuties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room2> Rooms { get; set; }
    }
}
